### ISSUE TITLE
Question on "switching_components"

### ISSUE THREAD

**Issue by jhpjhp1118** [mirkimirk/optimal_latin_hypercubes#1]
Nice to meet you sir.

I am studying the OLHD paper written by Park, with your code. 
This code helped me to understand the paper exactly. Thank you for that.

I just want to ask _**2 questions**_ about "switching_components" in your code (_step_2())
(https://github.com/mirkimirk/optimal_latin_hypercubes/blob/17d7167c5f595d9cf99841594e0c752476be2be4/src/model_code/latin_hypercubes.py#LL280C5-L288C6 )

1) I don't understand the reason why you made **only even-numbered combination**. As I understood, we can also generate odd-numbered combination, for example, exchanging 3 (or other odd-number...) design-variables between 2 sample points.

2) I think resultant "switching components" has somewhat **overlapping combinations** in that. For example, if dim=4, both index combination (0, 1) and (2, 3) will have the same result. I think we must not to consider overlapping combinations for exact implementation.

Best regards.

**Comment by mirkimirk** [comment]
Hey,

thank you so much for your comment! As I stated in the readme.md, I don't really understand Park's algorithm, specifically the part about the exchange-algorithm! I already thought that I must understand it wrong, and after testing some examples, I verified that this code does not produce good Latin Hypercubes.

Can you maybe explain to me how you understand that the exchange algorithm works? I started thinking about it a month ago again (really obsessed about it for a week again) but I just don't understand it. My own problems with understanding the algorithm are described in the Jupyter Notebook "OSE-submission.ipynb", under the chapter "Park's Puzzle". There you will find my answers to your two questions about my (wrong) way of thinking. If I better understand the exchange mechanism, I will correct the code in the near future.

Very grateful for your help! I always wanted to complete this project, this helps me a lot.

Best,
Mirkan

**Comment by jhpjhp1118** [comment]
I just read the Jupyter Notebook "OSE-submission.ipynb" and I understood your intention for the code.

I have some comments for that...

1) As you stated, some expressions in the paper written by Park are weird. Especially, I don't fully understand this statement in the paper too. It maybe includes some typos in the sentence, because just changing x_i1j1 to x_i2j1 & changing x_i2j2 to x_i1j2 don't satisfy the basic rule of LHD. I think carefully that, the author might confused english expression 'exchange' & 'change'. (It's just a guess). And also I don't understand why changing x_i2j2 to x_i1j2 should be considered, because it's not necessary. We should consider exchanging just 1 design-variable.
![image](https://github.com/mirkimirk/optimal_latin_hypercubes/assets/78991159/807a31e7-2ce8-4c12-b4f2-a79f5f17c7e1)

2) In my understand, we should consider also **odd-numbered combinations**, such as exchanging 1(or 3, 5, 7...) design-variables between 2 sample points (= "elements" in the paper). Considering only even-numbered combinations restricts exploring every case for exchanging design-variables of given active pair.

3) Maybe I can explain the reason why the number of different exchange is **(2^(d-1) - 1).**
![image](https://github.com/mirkimirk/optimal_latin_hypercubes/assets/78991159/da083e12-a5d1-41da-8f6a-121ae6830f7b)
Given 2 sample points(whose dimensions are d) as an active pair, naively, we can exchange all of design-variables each other. It means that, the number of 'naive' exchanges is **2^d**, because we have Yes / No options for exchanging each design-variables.
However, **we should eliminate 2 cases.(which means 2^d - 2)** 
i) Exchanging all design-variables each other
ii) Exchanging no design-variables each other
These cases don't make any differences for given MLHD after the exchange.
In addition, **we should eliminate overlapping combinations. (which means (2^d - 2)/2 = 2^(d-1) - 1)** 
For example, as I stated in original question, if d = 4, exchanging (0, 1) and (2, 3) have the same result. 
Given 2 sample points(d=4): 1234 / 5678
i) Exchanging (0, 1): 5634 / 1278
ii) Exchanging (2, 3): 1278 / 5634

**Comment by mirkimirk** [comment]
Hey!

1. Ok! My guess is also that the English here is a bit confused. Probably it is always meant to _exchange_ elements.
2. & 3. This derivation of (2^(d-1) - 1) makes a lot of sense I think! And I also did not at all consider the possibility of overlappings, that's a good point, and your example helped me too. I agree that my implementation using only even-numbered columns is too restrictive and must be wrong.

So, you propose that I should change the restriction from even-numbered columns into a restriction where only those exchanges are possible that you explained in (3.)? And we just ignore the sentences in (1.) that confused us?

I can start working on the code the coming weekend and think more about it then.

Thanks again!

**Comment by jhpjhp1118** [comment]
Yes, I think so.

Thank you for nice discussion :)

Best regards.
